# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qDQfw-hl0B0TxsBA-oix9HWvCYinYWo
"""

import hashlib
#import the library
text = "Siddu lives in Mumbai"
#text to be hashed
hash_object = hashlib.md5(text.encode())
#hash to be done in md5 algorithm
md5_hash = hash_object.hexdigest()
print(md5_hash)
#to obtain output of the text "Siddu lives in Mumbai"